    function resetStyle(button)
    {
        var all = document.getElementsByClassName("functionListButton");
        for (var i = 0; i < all.length; i++) 
        {
            all[i].classList.remove("functionListButtonActive");
        }
        button.classList.add("functionListButtonActive");
    }
    function editableTableLoad()
    {
        
    }
    function getTable(table,orderBy,orderType)
    {
        if(table=="report_ufficio_commerciale")
        {
            console.log("we");
            getEditableTable
            ({
                table:'report_ufficio_commerciale',
                editable: false,
                container:'containerSommarioArchivi',
                noFilterColumns:['data_scadenza','data_creazione','note','data_salvataggio'],
                foreignKeys:[['utente_salvataggio','utenti','id_utente','username']],
                orderBy:orderBy,
                orderType:orderType
            });
        }
        if(table=="produzione_bf_finiture")
        {
            getEditableTable
            ({
                table:'produzione_bf_finiture',
                readOnlyColumns:['id_finitura','commessa'],
                noInsertColumns:['id_finitura'],
                container:'containerGestioneAnagrafiche',
                foreignKeys:[['commessa','commesse','id_commessa','commessa']],
                orderBy:orderBy,
                orderType:orderType
            });
        }
        if(table=="produzione_bf_delta_articoli")
        {
            getEditableTable
            ({
                table:'produzione_bf_delta_articoli',
                readOnlyColumns:['id_articolo','commessa','utente','data_importazione'],
                noInsertColumns:['id_articolo'],
                noFilterColumns:['data_importazione'],
                container:'containerGestioneAnagrafiche',
                foreignKeys:[['utente','utenti','id_utente','username']],
                orderBy:orderBy,
                orderType:orderType
            });
        }	
        if(table=="produzione_bf_kit_bifacciali")
        {
            getEditableTable
            ({
                table:'produzione_bf_kit_bifacciali',
                readOnlyColumns:['id_kit_bifacciale','utente','data_importazione','commessa'],
                noInsertColumns:['id_kit_bifacciale','utente','data_importazione'],
                noFilterColumns:['data_importazione'],
                container:'containerGestioneAnagrafiche',
                foreignKeys:[['commessa','commesse','id_commessa','commessa'],['utente','utenti','id_utente','username']],
                orderBy:orderBy,
                orderType:orderType
            });
        }
        if(table=="produzione_bf_lavorazioni_x_v")
        {
            getEditableTable
            ({
                table:'produzione_bf_lavorazioni_x_v',
                readOnlyColumns:['id'],
                noInsertColumns:['id'],
                primaryKey:"id",
                container:'containerGestioneAnagrafiche',
                orderBy:orderBy,
                orderType:orderType
            });
        }
        if(table=="produzione_bf_lavorazioni_y_v")
        {
            getEditableTable
            ({
                table:'produzione_bf_lavorazioni_y_v',
                readOnlyColumns:['id'],
                noInsertColumns:['id'],
                primaryKey:"id",
                container:'containerGestioneAnagrafiche',
                orderBy:orderBy,
                orderType:orderType
            });
        }
        if(table=="elementi_elet")
        {
            getEditableTable
            ({
                table:'elementi_elet',
                readOnlyColumns:['id'],
                noInsertColumns:['id'],
                container:'containerGestioneAnagrafiche',
                orderBy:orderBy,
                orderType:orderType
            });
        }
    }